### ISSUE TITLE
Cannot create databse

### ISSUE THREAD

**Issue by Parshuram2** [koutto/jok3r#35]
The create database command python3 jok3r.py db gives the following error
Traceback (most recent call last):
 
 File "jok3r.py", line 44, in __init__
    controller.run()
  File "/root/jok3r/lib/controller/MainController.py", line 23, in run
    }.get(self.arguments.mode)(self.arguments, self.settings, self.sqlsess).run()
  File "/root/jok3r/lib/controller/DbController.py", line 68, in __init__
    del cmd2.Cmd.do_load
AttributeError: do_load

**Comment by Marduky** [comment]
i have the same problem

**Comment by dtql** [comment]
I faced the same issue. My guess is the cmd2 built-in commands do not exist. You can fix it by commenting or deleting lines 68 and 70 for "jok3r/DbController.py".

The 2 lines you need to comment/delete:
del cmd2.Cmd.do_load
del cmd2.Cmd.do_pyscript

**Comment by hansbonini** [comment]
Install package dependency `cmd2` via python pip or `python-cmd2` via your OS package manager

**Comment by b15h0p** [comment]
xxx@xxx:~# pip install cmd2
Requirement already satisfied: cmd2 in /usr/local/lib/python3.7/dist-packages (1.0.1)
Requirement already satisfied: setuptools>=34.4 in /usr/lib/python3/dist-packages (from cmd2) (44.0.0)
Requirement already satisfied: colorama>=0.3.7 in /usr/lib/python3/dist-packages (from cmd2) (0.4.3)
Requirement already satisfied: attrs>=16.3.0 in /usr/lib/python3/dist-packages (from cmd2) (19.3.0)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/lib/python3/dist-packages (from cmd2) (0.1.8)
Requirement already satisfied: pyperclip>=1.6 in /usr/lib/python3/dist-packages (from cmd2) (1.7.0)


Then:
[!] Unexpected error occured: do_load
Traceback (most recent call last):
  File "jok3r.py", line 44, in __init__
    controller.run()
  File "/root/jok3r/lib/controller/MainController.py", line 23, in run
    }.get(self.arguments.mode)(self.arguments, self.settings, self.sqlsess).run()
  File "/root/jok3r/lib/controller/DbController.py", line 68, in __init__
    del cmd2.Cmd.do_load
AttributeError: do_load

Any other ideas?

**Comment by b15h0p** [comment]
Comment/delete lines in "/root/jok3r/lib/controller/DbController.py" as dtql mentioned above is what resolved this issue.

**Comment by ashishp99** [comment]
> I faced the same issue. My guess is the cmd2 built-in commands do not exist. You can fix it by commenting or deleting lines 68 and 70 for "jok3r/DbController.py".
> 
> The 2 lines you need to comment/delete:
> del cmd2.Cmd.do_load
> del cmd2.Cmd.do_pyscript

yes your trick working bro.... thank you so much ....

**Comment by TofuWand** [comment]
The solution that worked for some of you didn't work for me.
