### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by S3cButch3r** [koutto/jok3r#37]
While running the command command "python3 jok3r.py attack -t http://targetwebsite.com/ --add2db test " from the docker, Following python error appears. It seems like the "sys" module is not being imported.

> [*] URL given as target, targeted service is HTTP
[!] Unable to resolve scanme.nmap.org
[!] Unexpected error occured: name 'sys' is not defined
Traceback (most recent call last):
  File "/root/jok3r/lib/controller/AttackController.py", line 130, in __run_for_single_target
    target = Target(service, self.settings.services)
  File "/root/jok3r/lib/core/Target.py", line 45, in __init__
    self.__init_with_url()
  File "/root/jok3r/lib/core/Target.py", line 68, in __init_with_url
    raise TargetException('Unable to resolve {}'.format(url.hostname))
lib.core.Exceptions.TargetException: Unable to resolve scanme.nmap.org
>
> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "jok3r.py", line 44, in __init__
    controller.run()
  File "/root/jok3r/lib/controller/MainController.py", line 23, in run
    }.get(self.arguments.mode)(self.arguments, self.settings, self.sqlsess).run()
  File "/root/jok3r/lib/controller/AttackController.py", line 86, in run
    self.__run_for_single_target(args)
  File "/root/jok3r/lib/controller/AttackController.py", line 133, in __run_for_single_target
    sys.exit(1)
NameError: name 'sys' is not defined

**Comment by decart-hub** [comment]
easy fix, just import sys..
