### ISSUE TITLE
[!] Unexpected error occured: (sqlite3.OperationalError) no such column: services.html_title

### ISSUE THREAD

**Issue by Mi-Al** [koutto/jok3r#4]
Hello! I use jok3r in Docker. When I start checking (I tried http and mysql), for example:

```
python3 jok3r.py db
mission -a sp
CTRL+d
python3 jok3r.py attack -t https://site.ru --add sp
```

I always got the error:

```
[*] Results from this attack will be saved under mission "sp" in database
[!] Unexpected error occured: (sqlite3.OperationalError) no such column: services.html_title
[SQL: SELECT services.id AS services_id, services.name AS services_name, services.port AS services_port, services.protocol AS services_protocol, services.url AS services_url, services.up AS services_up, services.banner AS services_banner, services.html_title AS services_html_title, services.http_headers AS services_http_headers, services.web_technos AS services_web_technos, services.comment AS services_comment, services.host_id AS services_host_id 
FROM services JOIN hosts ON hosts.id = services.host_id JOIN missions ON missions.id = hosts.mission_id 
WHERE hosts.ip = ? AND missions.name = ? AND services.name = ? AND services.port = ? AND services.protocol = ? AND services.url = ?
 LIMIT ? OFFSET ?]
[parameters: (1475088592, 'sp', 'http', 443, 'TCP', 'https://site.ru', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: services.html_title

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "jok3r.py", line 44, in __init__
    controller.run()
  File "/root/jok3r/lib/controller/MainController.py", line 23, in run
    }.get(self.arguments.mode)(self.arguments, self.settings, self.sqlsess).run()
  File "/root/jok3r/lib/controller/AttackController.py", line 86, in run
    self.__run_for_single_target(args)
  File "/root/jok3r/lib/controller/AttackController.py", line 164, in __run_for_single_target
    req.add_target(target)
  File "/root/jok3r/lib/requester/ServicesRequester.py", line 272, in add_target
    .filter(Service.url == target.get_url()).first()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: services.html_title
[SQL: SELECT services.id AS services_id, services.name AS services_name, services.port AS services_port, services.protocol AS services_protocol, services.url AS services_url, services.up AS services_up, services.banner AS services_banner, services.html_title AS services_html_title, services.http_headers AS services_http_headers, services.web_technos AS services_web_technos, services.comment AS services_comment, services.host_id AS services_host_id 
FROM services JOIN hosts ON hosts.id = services.host_id JOIN missions ON missions.id = hosts.mission_id 
WHERE hosts.ip = ? AND missions.name = ? AND services.name = ? AND services.port = ? AND services.protocol = ? AND services.url = ?
 LIMIT ? OFFSET ?]
[parameters: (1475088592, 'sp', 'http', 443, 'TCP', 'https://site.ru', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by koutto** [comment]
Hello.
I am currently actively working on the code, testings and debugs ! The Docker image might be a lot unstable because all modifications in code are not pushed to the Docker image.

So, for your problem, i recommend to update manually: git pull
And then to remove the database file "local.db" to restart from a fresh database to make sure database architecture changes are taken into account.

**Comment by koutto** [comment]
New version is released (still in beta).
You should just pull the new Docker container.
