### ISSUE TITLE
Unable to load db mode jok3r

### ISSUE THREAD

**Issue by r3dpars3c** [koutto/jok3r#48]
root@kali:/home/kali/bug-bounty/jok3r# python3 jok3r.py db

                          `-:/++++/:-.    .-:/++++/:-`                                    
                        .:ohdddmmmmdd.\  /.dddmmmmdddho:.                                
                      `:ydmmmmmmmmmmmmm\/mmmmmmmmmmmmmmdy:`                         
                     `+dmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd+`                     
                    +dyo+++oshmmmmmmmmmmmmmmmmmmmmhso+++oyd+                    
                  -+-         .dmmmmmmmmmmmmmmmmd.         -+-                  
                 ``           `dmmmmmmmmmmmmmmmmd`           ``                 
                              `dmmmmmmmmmmmmmmmmd`                              
                              `ymmmmmmmmmmmmmmmmy`                              
                                .+dmmmmmmmmmmd+.                                
                                   /dmmmmmmd/                                   
                                    `odmmdo`                                    
                                      .hh.                                      
                                                        
                                                                   
                       ██╗ ██████╗ ██╗  ██╗██████╗ ██████╗ 
                       ██║██╔═══██╗██║ ██╔╝╚════██╗██╔══██╗
                       ██║██║   ██║█████╔╝  █████╔╝██████╔╝
                  ██   ██║██║   ██║██╔═██╗  ╚═══██╗██╔══██╗
                  ╚█████╔╝╚██████╔╝██║  ██╗██████╔╝██║  ██║  v3.0 beta 2
                   ╚════╝  ╚═════╝ ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝ 
                  
                  [ Network & Web Pentest Automation Framework ]

[!] Unexpected error occured: do_load
Traceback (most recent call last):
  File "jok3r.py", line 44, in __init__
    controller.run()
  File "/home/kali/bug-bounty/jok3r/lib/controller/MainController.py", line 18, in run
    {
  File "/home/kali/bug-bounty/jok3r/lib/controller/DbController.py", line 68, in __init__
    del cmd2.Cmd.do_load
AttributeError: do_load

**Comment by TofuWand** [comment]
I'm not able to get db to work at all. I even tried the methods used by the other issue posted about the db.
