### ISSUE TITLE
Error starting jok3r.py

### ISSUE THREAD

**Issue by pedrodj** [koutto/jok3r#6]
root@DESKTOP-DDJ9GB4:/home/pedro/jok3r# python3 jok3r.py
Traceback (most recent call last):
  File "jok3r.py", line 13, in <module>
    from lib.controller.MainController import MainController
  File "/home/pedro/jok3r/lib/controller/__init__.py", line 6, in <module>
    from .DbController import *
  File "/home/pedro/jok3r/lib/controller/DbController.py", line 8, in <module>
    import cmd2
  File "/usr/local/lib/python3.7/dist-packages/cmd2/__init__.py", line 13, in <module>
    from .cmd2 import Cmd, Statement, EmptyStatement, categorize
  File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 50, in <module>
    from .clipboard import can_clip, get_paste_buffer, write_to_paste_buffer
  File "/usr/local/lib/python3.7/dist-packages/cmd2/clipboard.py", line 28, in <module>
    _ = pyperclip.paste()
  File "/usr/local/lib/python3.7/dist-packages/pyperclip/__init__.py", line 638, in lazy_load_stub_paste
    return paste()
  File "/usr/local/lib/python3.7/dist-packages/pyperclip/__init__.py", line 479, in paste_wsl
    close_fds=True)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'powershell.exe': 'powershell.exe'

Ok Kali Linux fully Updated under Windows 10 (with powershell installed)

Any help?

**Comment by koutto** [comment]
Use Docker image instead as explained in "Installation" section.
