### ISSUE TITLE
python TypeError on nmap check

### ISSUE THREAD

**Issue by parfeniukink** [koutto/jok3r#60]
OS: MacOS Monterey 12.1
Chip: M1

```
[*] URL given as target, targeted service is HTTP
[*] Check if service is reachable...
[*] Grab service info for [host 193.29.204.164 | port 443/tcp | service http] via Nmap...
Nmap scan failed: pcap_open_live(eth0, 256, 0, 200) FAILED. Reported error: eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Function not implemented.  Will wait 5 seconds then retry.
pcap_open_live(eth0, 256, 0, 200) FAILED. Reported error: eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Function not implemented.  Will wait 25 seconds then retry.
Call to pcap_open_live() failed three times. There are several possible reasons for this, depending on your operating system:
LINUX: If you are getting Socket type not supported, try modprobe af_packet or recompile your kernel with PACKET enabled.
 *BSD:  If you are getting device not configured, you need to recompile your kernel with Berkeley Packet Filter support.  If you are getting No such file or directory, try creating the device (eg cd /dev; MAKEDEV <device>; or use mknod).
*WINDOWS:  Nmap only supports ethernet interfaces on Windows for most operations because Microsoft disabled raw sockets as of Windows XP SP2.  Depending on the reason for this error, it is possible that the --unprivileged command-line argument will help.
SOLARIS:  If you are trying to scan localhost or the address of an interface and are getting '/dev/lo0: No such file or directory' or 'lo0: No DLPI device found', complain to Sun.  I don't think Solaris can support advanced localhost scans.  You can probably use "-Pn -sT localhost" though.


QUITTING!

[!] Unexpected error occured: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "jok3r.py", line 44, in __init__
    controller.run()
  File "/root/jok3r/lib/controller/MainController.py", line 23, in run
    }.get(self.arguments.mode)(self.arguments, self.settings, self.sqlsess).run()
  File "/root/jok3r/lib/controller/AttackController.py", line 86, in run
    self.__run_for_single_target(args)
  File "/root/jok3r/lib/controller/AttackController.py", line 141, in __run_for_single_target
    or args.nmap_banner_grab == 'on'))
  File "/root/jok3r/lib/core/Target.py", line 352, in smart_check
    self.service.banner = NetUtils.clean_nmap_banner(nmap_info['banner'])
TypeError: 'NoneType' object is not subscriptable
root@jok3r-docker:~/jok3r#
```

**Comment by savager** [comment]
Just ran across this, any solve?

**Comment by parfeniukink** [comment]
> Just ran across this, any solve?

Yeap. Try to use this 3.0beta image instead
https://hub.docker.com/layers/koutto/jok3r/3.0beta/images/sha256-bf21fd640c2ad57c72cfefe798c27474b3dbcd15cf79f87a7b57c06a09e4c45f?context=explore

**Comment by savager** [comment]
Thanks very much
